import{a as m,S as L,i as l}from"./assets/vendor-BzajH6aU.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const g of r.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&o(g)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();m.defaults.baseURL="https://pixabay.com/api/";const c={key:"46481963-10f537a41063d6fd7fead7408",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15};async function f(){const a=await m.get("",{params:c});return a.data.totalPages=Math.floor(a.data.totalHits/c.per_page)+1,a.data}function P(a){return c.page=1,c.q=a,f()}function b(){return c.page+=1,f()}function y(a){var e="";for(const s of a)e+=`<li class="gallery-item">
      <a class="gallery-link" href="${s.largeImageURL}">
        <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}">
      </a>
      <div class="gallery-descr">
        <div><span>Likes</span>${s.likes}</div>
        <div><span>Views</span>${s.views}</div>
        <div><span>Comments</span>${s.comments}</div>
        <div><span>Downloads</span>${s.downloads}</div>
      </div>
    </li>`;return e}function h(a){const{loadButton:e,curPage:s,totalPages:o,iziToast:t,msg:r}=a;s<o?e.classList.remove("visually-hidden"):(e.classList.add("visually-hidden"),t.info({message:r}))}const p=new L(".gallery a",{overlayOpacity:.8,className:"gallery-wrapper",captionsData:"alt",captionDelay:250});l.settings({class:"toast",position:"topRight",drag:!1});const d=document.querySelector(".load_more span"),i=document.querySelector(".gallery");var u=1;const n=document.querySelector(".load_more button"),v="We're sorry, but you've reached the end of search results.";document.getElementById("search-form").addEventListener("submit",a=>{a.preventDefault();const e=a.currentTarget,s=e.elements.queryStr.value.trim();if(s===""){e.reset();return}d.classList.remove("visually-hidden"),i.classList.add("visually-hidden"),i.innerHTML="",n.classList.add("visually-hidden"),P(s).then(o=>{o.total==0||o.hits.length==0?l.error({message:"Sorry, there are no images matching your search query. Please try again!"}):(u=1,i.innerHTML=y(o.hits),i.classList.remove("visually-hidden"),p.refresh(),h({loadButton:n,curPage:u,totalPages:o.totalPages,iziToast:l,msg:v}))}).catch(o=>{l.error({message:o.message})}).finally(()=>{d.classList.add("visually-hidden"),e.reset()})});n.addEventListener("click",a=>{a.preventDefault(),d.classList.remove("visually-hidden"),n.classList.add("visually-hidden"),b().then(e=>{u+=1,i.insertAdjacentHTML("beforeend",y(e.hits)),p.refresh();const s=i.querySelector("li:last-child").getBoundingClientRect();window.scrollBy(0,s.height*2),h({loadButton:n,curPage:u,totalPages:e.totalPages,iziToast:l,msg:v})}).catch(e=>{l.error({message:e.message})}).finally(()=>{d.classList.add("visually-hidden")})});
//# sourceMappingURL=index.js.map
